services:
  sync:
    depends_on:
      - rabbitmq
      - amid
      - auth
      - dird
      - confd
      - phoned
    environment:
      TARGETS: "rabbitmq:5672 amid:9491 confd:9486 phoned:9498 phoned:9499 dird:9489 auth:9497"
