services:
  sync:
    depends_on:
      - auth
      - dird
      - rabbitmq
      - phoned
    environment:
      TARGETS: "rabbitmq:5672 phoned:9499 dird:9489 auth:9497"

  phoned:
    volumes:
      - "./etc/wazo-phoned/conf.d/20-http-disabled.yml:/etc/wazo-phoned/conf.d/20-http-disabled.yml"
