services:
  sync:
    depends_on:
      - auth
      - dird
      - phoned
    environment:
      TARGETS: "phoned:9498 phoned:9499 dird:9489 auth:9497"

  phoned:
    volumes:
      - "./etc/wazo-phoned/conf.d/20-authorized-subnets.yml:/etc/wazo-phoned/conf.d/20-authorized-subnets.yml"
